import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Card, CardHeader, Container, Grid, Button, TextField, FormControl, FormLabel, Typography } from "@mui/material"
import { useState, ChangeEventHandler, useRef } from "react"
import { getData } from './parser'
import { PhoneTable } from "./PhoneTable"

const Home: NextPage = () => {
  const [numbers, setNumbers] = useState<string[]>([])
  const [inputNumber, setInputNumber] = useState<string>("")

  const [onEdit, setOnEdit] = useState<boolean>(false)
  const [editNumber, setEditNumber] = useState<string>("")

  const handleChange: ChangeEventHandler<HTMLInputElement> = (event) => {
    setInputNumber(event.target.value)
  }

  const handleEditChange: ChangeEventHandler<HTMLInputElement> = (event) => {
    setInputNumber(event.target.value)
  }

  const handleAdd = () => {
    setNumbers(numbers.concat(inputNumber))
    setEditNumber("")
  }

  const [rows, setRows] = useState<string[]>([])
  const handleFile: ChangeEventHandler<HTMLInputElement> = (event) => {
    if (event.target.files) {
      if (event.target.files[0]) {
        getData(event.target.files[0])
          .then((res: any) => {
            console.log("res", res)
            if (res.data) {
              if (res.data.Sheet1) {
                if (res.data.Sheet1.length > 0) {
                  let totalRows: string[] = []
                  res.data.Sheet1.forEach((item: any) => {
                    totalRows.push(`+251${String(Object.values(item)[0]).replace('+251', '')}`)
                  })
                  setRows(totalRows)
                }
              }
            }
          })
      }
    }
  }

  const fileRef = useRef<any>()
  const toggelFile = () => fileRef.current.click()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input type="file" ref={fileRef} hidden onChange={handleFile} />
      <main className={styles.main}>
        <Grid container width='85%' spacing={4} justifyContent="center">
          <Grid md={8} container justifyContent="space-between" sx={{
            pl: 4,
            pr: 4,
            borderTopLeftRadius: 5,
            borderTopRightRadius: 5,
          }}>
            <Grid item md={9}>
              <Typography variant='h4' align="left">
                M0 for Sending Bulk SMS
              </Typography>
            </Grid>
            <Grid md={3} item>
              <Button variant="contained" color="success" fullWidth onClick={toggelFile}>
                Select Excel File
              </Button>
            </Grid>
          </Grid>
          <Grid item md={8} sx={{
            pl: 4,
            pr: 4,
            mb: 0
          }}>
            <FormControl fullWidth>
              <FormLabel>Enter Text Here</FormLabel>
              <TextField rows={4} multiline />
            </FormControl>
          </Grid>
          <Grid item md={8} sx={{
            pl: 4,
            pr: 4,
            borderBottomLeftRadius: 5,
            borderBottomRightRadius: 5,
          }}>
            <PhoneTable rows={rows} setRows={setRows} />
          </Grid>
          {rows.length > 0 ? (
            <Grid item md={8} sx={{
              pl: 4,
              pr: 4,
              display: "flex",
              justifyContent: "space-between",
              mt: -2,
            }}
            >
              <Button color="warning" variant="contained" onClick={() => setRows([])}>
                Cancel
              </Button>
              <Button color="primary" variant="contained">
                Send
              </Button>
            </Grid>
          ) : <></>}
        </Grid>
      </main>
    </div>
  )
}

export default Home
